package com.gns.software.system.model;

import java.util.Date;

public class Template {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.id
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.name
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.folderid
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private String folderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.type
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.level
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private String level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.size
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Double size;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.createtime
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.archivetime
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Date archivetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.archivepath
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private String archivepath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.parentid
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Integer parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.order
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Integer order;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.priority
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column g_datastore.status
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.id
	 * @return  the value of g_datastore.id
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.id
	 * @param id  the value for g_datastore.id
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.name
	 * @return  the value of g_datastore.name
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.name
	 * @param name  the value for g_datastore.name
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.folderid
	 * @return  the value of g_datastore.folderid
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public String getFolderid() {
		return folderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.folderid
	 * @param folderid  the value for g_datastore.folderid
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setFolderid(String folderid) {
		this.folderid = folderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.type
	 * @return  the value of g_datastore.type
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.type
	 * @param type  the value for g_datastore.type
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.level
	 * @return  the value of g_datastore.level
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.level
	 * @param level  the value for g_datastore.level
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.size
	 * @return  the value of g_datastore.size
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Double getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.size
	 * @param size  the value for g_datastore.size
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setSize(Double size) {
		this.size = size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.createtime
	 * @return  the value of g_datastore.createtime
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.createtime
	 * @param createtime  the value for g_datastore.createtime
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.archivetime
	 * @return  the value of g_datastore.archivetime
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Date getArchivetime() {
		return archivetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.archivetime
	 * @param archivetime  the value for g_datastore.archivetime
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setArchivetime(Date archivetime) {
		this.archivetime = archivetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.archivepath
	 * @return  the value of g_datastore.archivepath
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public String getArchivepath() {
		return archivepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.archivepath
	 * @param archivepath  the value for g_datastore.archivepath
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setArchivepath(String archivepath) {
		this.archivepath = archivepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.parentid
	 * @return  the value of g_datastore.parentid
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Integer getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.parentid
	 * @param parentid  the value for g_datastore.parentid
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.order
	 * @return  the value of g_datastore.order
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Integer getOrder() {
		return order;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.order
	 * @param order  the value for g_datastore.order
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setOrder(Integer order) {
		this.order = order;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.priority
	 * @return  the value of g_datastore.priority
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.priority
	 * @param priority  the value for g_datastore.priority
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column g_datastore.status
	 * @return  the value of g_datastore.status
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column g_datastore.status
	 * @param status  the value for g_datastore.status
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}