package com.gns.software.system.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.id
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.username
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.userpassword
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    private String userpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuser.deptid
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    private Long deptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.id
     *
     * @return the value of cuser.id
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.id
     *
     * @param id the value for cuser.id
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.username
     *
     * @return the value of cuser.username
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.username
     *
     * @param username the value for cuser.username
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.userpassword
     *
     * @return the value of cuser.userpassword
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.userpassword
     *
     * @param userpassword the value for cuser.userpassword
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuser.deptid
     *
     * @return the value of cuser.deptid
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    public Long getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuser.deptid
     *
     * @param deptid the value for cuser.deptid
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    public void setDeptid(Long deptid) {
        this.deptid = deptid;
    }
}