server:
  port: 8080
  servlet:
   context-path: /demoWeb
   
logging:
  level: 
    learning: trace
   
spring:
    datasource:
        name: test
      #  url: jdbc:mysql://127.0.0.1:3306/demoweb?useUnicode=true&characterEncoding=utf-8&useSSL=true
      #  url: jdbc:mysql://127.0.0.1:3306/demoweb?useSSL=false&useUnicode=true&characterEncoding=UTF-8 
        url: jdbc:mysql://127.0.0.1:3306/demoweb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true 
        username: root
        password: success
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        druid:
           url: jdbc:mysql://127.0.0.1:3306/demoweb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true 
           username: root
           password: success
           driver-class-name: com.mysql.cj.jdbc.Driver
    #thymeleaf 基本配置
    thymeleaf:  
        cache: false  
        prefix: classpath:/templates/  
        suffix: .html  
        encoding: UTF-8  
        servlet:
          content-type: text/html  
        mode: HTML5  
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.winter.model
  
mybatis:
  #实体类所做包
  type-aliases-package: com.winter.model
  #mapper.xml所在位置
  #mapper-locations: classpath:mappers/*.xml
  mapper-locations: classpath:com/winter/mapper/*.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    