package com.gns.software.system.mapper;

import com.gns.software.system.model.Datastore;

public interface DatastoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_datastore
     *
     * @mbg.generated Sun Sep 29 15:02:44 CST 2019
     */
    int insert(Datastore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_datastore
     *
     * @mbg.generated Sun Sep 29 15:02:44 CST 2019
     */
    int insertSelective(Datastore record);
}