package com.gns.software.system.mapper;

import com.gns.software.system.model.Template;

public interface TemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table g_datastore
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	int insert(Template record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table g_datastore
	 * @mbg.generated  Sun Sep 29 15:00:41 CST 2019
	 */
	int insertSelective(Template record);
}