package com.gns.software.system.mapper;

import com.gns.software.system.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuser
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuser
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    int insertSelective(User record);
}